# 打包镜像，上传到指定URL(脚本使用：miniserve上传服务)
name: Upload

on:
  workflow_dispatch:
    inputs:
      platform:
        type: choice
        description: "选择镜像架构"
        options: 
          - amd64
          - arm64
        default: arm64
      # 我有多个需要上传的URL，所以配置成选项。
      url_tag:
        type: choice
        description: "选择上传URL"
        options: 
          - 香橙派
          - 腾讯云
      docker_images:
        description: '请填写docker镜像名称 多个用英文逗号分开'
        required: true
        default: 'snowdreamtech/frps:latest'  # 设置默认的 Docker 镜像列表

env: 
  # 上传token
  Authorization: "${{ secrets.Authorization }}"
  # 上传链接，有其他参数自行添加
  UPLOADURL1: "${{ secrets.UPLOADURL1 }}"
  UPLOADURL2: "${{ secrets.UPLOADURL2 }}"

jobs:
  pull_and_package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup WARP
      uses: fscarmen/warp-on-actions@v1.1

    - name: Pull Docker Images and Package
      run: |
        pf="${{ github.event.inputs.platform }}"
        url_tag="${{ github.event.inputs.url_tag }}"
        if [ "$url_tag" == "香橙派" ];then
          UPLOADURL=$UPLOADURL1
        else
          UPLOADURL=$UPLOADURL2
        fi
        images="${{ github.event.inputs.docker_images }}"
        IFS=',' read -r -a image_array <<< "$images"
        for image in "${image_array[@]}"; do
          docker pull "${image}" --platform "linux/${pf}"
          # 提取包含可能的标签或sha256的部分
          image_with_tag_or_sha=${image##*/}
          # 提取去掉标签或sha256的镜像名
          image_name=${image_with_tag_or_sha%%[:@]*}
          file_path="${image_name}-image.tar"
          docker save "${image}" -o $file_path
          # 获取完整路径
          if command -v realpath > /dev/null; then
              absolute_path=$(realpath "$file_path")
          elif command -v readlink > /dev/null; then
              absolute_path=$(readlink -f "$file_path")
          else
              echo "获取完整路径失败."
              exit 1
          fi
          # 上传
          curl --progress-bar -X POST -H "Authorization: ${Authorization}" "$UPLOADURL" -F "path=@$absolute_path"
        done

    - name: Clean up intermediate files
      run: |
        rm *-image.tar